name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0

dev_dependencies:
  http: ^0.13.3

dependency_overrides:
  firebase_core: 
    path: ../../../firebase_core/firebase_core/
  firebase_core_web: 
    path: ../../../firebase_core/firebase_core_web/
  firebase_core_platform_interface: 
    path: ../../../firebase_core/firebase_core_platform_interface/
  firebase_auth_web: 
    path: ../../firebase_auth_web/
  firebase_auth: 
    path: ../../firebase_auth/
  firebase_auth_platform_interface: 
    path: ../../firebase_auth_platform_interface/

flutter:
  uses-material-design: true
